### ISSUE TITLE
How is the extension supposed to work?

### ISSUE THREAD

**Issue by quasipedia** [war1025/Currency-Converter#1]
I installed the extension on an Ubuntu 12.04 machine, using `extensions.gnome.org`. The installation worked fine, but I can't understand how to access the converter window (it is not in the tray, the toolbar or the app menu)....

**Comment by war1025** [comment]
It's a search provider for the overview. Go into the shell overview and type into the search bar. "12 USD to EUR" for example. Sorry, perhaps I should have been more explicit about that in the description.

**Comment by quasipedia** [comment]
Thanks, now I see it and I feel totally dumb for not having got it before! 
I'm posting some feedback in a separate issue then. Thanks!
